swagger: '2.0'
info:
  version: '1.0.0'
  title: My API
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /upload:
    post:
      summary: Uploads an image
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        200:
          description: Success
