swagger: "2.0"
info:
  title: AWS Task Api
  description: AWS Task API documentation
  version: 1.0
  contact:
    email: hrvoje.vukov@akvelon.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  servers:
    -url: "http://localhost:4000/"
    description: This is Aws Task Server

schemes: [http,https]

paths:
#File Upload
  /upload:
    post:
      summary: Uploads a file
      consumes:
         - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: The file to upload
      responses:
        200:
          description: "OK"
        400:
          description: "User error"
        422:
          description: "Wrong file type"
        500:
          description: "Server error"

#Check task state
  paths:
  /state/{id}:
    get:
      summary: Get task status of image processing
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the task to retrieve
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              taskId:
                type: string
              taskState:
                type: string
              originalS3Path:
                type: string
              processedS3Path:
                type: string
        400:
          description: Image does not exist
        500:
          description: Internal server error


